[package]
name = "refinery"
version = "0.2.0-alpha.2"
authors = ["Katharina Fey <kookie@spacekookie.de>", "Jo√£o Oliveira <hello@jxs.pt>"]
license = "MIT OR Apache-2.0"
description = "Powerful SQL migration toolkit for Rust"
readme = "README.md"
documentation = "https://docs.rs/refinery/"
repository = "https://github.com/rust-db/refinery"
keywords = ["database", "sql", "migrations", "orm"]
categories = ["database"]
edition = "2018"

[features]
default = []
rusqlite = ["refinery-migrations/sync", "refinery-migrations/rusqlite", "barrel/sqlite3"]
postgres = ["refinery-migrations/sync", "refinery-migrations/postgres", "barrel/pg"]
mysql = ["refinery-migrations/sync", "refinery-migrations/mysql", "barrel/mysql"]
tokio-postgres = ["refinery-migrations/async", "refinery-migrations/tokio-postgres", "refinery-migrations/tokio", "barrel/pg"]
mysql_async = ["refinery-migrations/async", "refinery-migrations/mysql_async", "barrel/pg"]

#testing features
trusqlite = ["rusqlite", "mod_migrations/sqlite"]
tpostgres = ["ttpostgres", "postgres", "mod_migrations/pg"]
tmysql = ["mysql", "mod_migrations/mysql"]
tttokio-postgres = ["tokio", "ttokio-postgres", "tokio-postgres", "mod_migrations/pg"]
ttmysql_async = ["tokio", "mysql_async", "tmysql_async", "mod_migrations/mysql"]

[dependencies]
refinery-migrations = { version = "0.2.0-alpha.2", path = "../refinery_migrations" }
refinery-macros= { version = "0.2.0-alpha.2", path = "../refinery_macros" }
barrel = "0.5.3"
# hack because there's no optional dev-dependencies
# and rust 1.39 doesn't support #[non_exhaustive], TODO: remove when previous version is 1.40
tokio = { version = "0.2", features = ["full"], optional = true }
ttokio-postgres = {package = "tokio-postgres", version = "0.5.0", optional = true }
tmysql_async = { package = "mysql_async", version = "0.21", optional = true }
ttpostgres = {package = "postgres", version = "0.15", optional = true }

[dev-dependencies]
ttrusqlite = {package = "rusqlite", version = "0.21"}
futures = "0.3.1"
ttmysql = {package = "mysql", version = "16.0"}

mod_migrations = {path = "./tests/mod_migrations"}
chrono = "0.4.6"
assert_cmd = "0.11.1"
predicates = "1.0.1"
tempfile = "3.1.0"

# [package.metadata.docs.rs]
# features = ["postgres", "mysql", "sqlite", "extras"]
# no-default-features = true
