[package]
name = "refinery"
version = "0.1.10"
authors = ["Katharina Fey <kookie@spacekookie.de>", "Jo√£o Oliveira <hello@jxs.pt>"]
license = "MIT OR Apache-2.0"
description = "Powerful SQL migration toolkit for Rust"
readme = "README.md"
documentation = "https://docs.rs/refinery/"
repository = "https://github.com/rust-db/refinery"
keywords = ["database", "sql", "migrations", "orm"]
categories = ["database"]
edition = "2018"

[features]
default = []
rusqlite = ["refinery-migrations/rusqlite", "barrel/sqlite3"]
postgres = ["refinery-migrations/postgres", "barrel/pg"]
mysql = ["refinery-migrations/mysql", "barrel/mysql"]

#testing features
trusqlite = ["mysql", "postgres", "rusqlite", "refinery-migrations/mysql", "refinery-migrations/postgres", "refinery-migrations/rusqlite", "mod_migrations/sqlite"]
tpostgres = ["mysql", "postgres", "rusqlite", "refinery-migrations/mysql", "refinery-migrations/postgres", "refinery-migrations/rusqlite", "mod_migrations/pg"]
tmysql = ["mysql", "postgres", "rusqlite", "refinery-migrations/mysql", "refinery-migrations/postgres", "refinery-migrations/rusqlite", "mod_migrations/mysql"]

[dependencies]
refinery-migrations= { version = "0.1.0", path = "../refinery_migrations" }
refinery-macros= { version = "0.1.0", path = "../refinery_macros" }
barrel = "0.5.3"

[dev-dependencies]
ttrusqlite = {package = "rusqlite", version = "0.18.0"}
ttpostgres = {package = "postgres", version = "0.15"}
ttmysql = {package = "mysql", version = "16.0"}

mod_migrations = {path = "./tests/mod_migrations"}
chrono = "0.4.6"
assert_cmd = "0.11.1"
predicates = "1.0.1"

# [package.metadata.docs.rs]
# features = ["postgres", "mysql", "sqlite", "extras"]
# no-default-features = true
