[package]
name = "refinery"
version = "0.4.0"
authors = ["Katharina Fey <kookie@spacekookie.de>", "Jo√£o Oliveira <hello@jxs.pt>"]
license = "MIT"
description = "Powerful SQL migration toolkit for Rust"
readme = "README.md"
documentation = "https://docs.rs/refinery/"
repository = "https://github.com/rust-db/refinery"
keywords = ["database", "sql", "migrations", "orm"]
categories = ["database"]
edition = "2018"

[features]
default = []
rusqlite-bundled = ["refinery-core/rusqlite-bundled"]
rusqlite = ["refinery-core/rusqlite"]
postgres = ["refinery-core/postgres"]
mysql = ["refinery-core/mysql"]
tokio-postgres = ["refinery-core/tokio-postgres"]
mysql_async = ["refinery-core/mysql_async"]
tokio = ["refinery-core/tokio"]

[dependencies]
refinery-core= { version = "0.4.0", path = "../refinery_core" }
refinery-macros= { version = "0.4.0", path = "../refinery_macros" }

[dev-dependencies]
tokio-compat-02 = "~0.1.2"
barrel = { version = "0.6", features = ["sqlite3", "pg", "mysql"] }
futures = "0.3"
assert_cmd = "0.12"
predicates = "1"
tempfile = "3"
chrono = "0.4"
