[package]
name = "refinery_cli"
version = "0.2.0"
authors = ["Katharina Fey <kookie@spacekookie.de>", "Jo√£o Oliveira <hello@jxs.pt>"]
license = "MIT OR Apache-2.0"
description = "Provides the CLI for the Refinery crate"
documentation = "https://docs.rs/refinery/"
repository = "https://github.com/rust-db/refinery"
readme = "README.md"
keywords = ["refinery", "migrations", "cli"]
edition = "2018"

[[bin]]
name = "refinery"
path = "src/main.rs"

[features]
default = ["mysql", "postgresql", "sqlite-bundled"]
postgresql = ["refinery/postgres"]
mysql = ["refinery/mysql"]
sqlite = ["refinery/rusqlite"]
sqlite-bundled = ["refinery/rusqlite-bundled"]

[dependencies]
refinery = { version = "0.2", path = "../refinery", default-features = false }
clap = { version = "2", features = ["wrap_help"] }
exitfailure = "0.5"
human-panic = "1"
toml = "0.5"
env_logger = "0.7"
log = "0.4"
anyhow = "1"
regex = "1"
walkdir = "2.3.1"

[dev-dependencies]
predicates = "1"
assert_cmd = "0.12"
