[package]
name = "refinery_cli"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
license = "MIT OR Apache-2.0"
description = "Provides the CLI for the Refinery crate"
readme = "README.md"
keywords = ["refinery", "migrations", "cli"]

[[bin]]
name = "refinery"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
clap = { version = "^2.30", features = ["wrap_help"] }
refinery = { path = "../refinery" }

[features]
# default = ["postgres", "sqlite", "mysql"]
# lint = ["clippy"]
# postgres = ["diesel/postgres", "infer_schema_internals/postgres", "url"]
# sqlite = ["diesel/sqlite", "infer_schema_internals/sqlite"]
# mysql = ["diesel/mysql", "infer_schema_internals/mysql", "url"]

# [[test]]
# name = "tests"

# [badges]
# travis-ci = { repository = "diesel-rs/diesel" }
# appveyor = { repository = "diesel-rs/diesel" }