[package]
name = "refinery-macros"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>", "Jo√£o Oliveira <hello@jxs.pt>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.12"
syn = {version="0.15.34", features=["full"]}
proc-macro2 = "0.4.29"
lazy_static = "1.3.0"
log = "0.4.6"
barrel = "0.5.7"
refinery-migrations = {path="../refinery_migrations/"}

[dev-dependencies]
barrel = {version = "0.5.7", features = ["mysql"]}
