[package]
name = "refinery-macros"
version = "0.2.0"
authors = ["Katharina Fey <kookie@spacekookie.de>", "Jo√£o Oliveira <hello@jxs.pt>"]
description = "This crate should not be used directly, it is internaly related to Refinery"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/refinery/"
repository = "https://github.com/rust-db/refinery"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
refinery-core= { version = "0.2.0", path = "../refinery_core" }
quote = "1"
syn = { version = "1", features=["full"] }
proc-macro2 = "1"
regex = "1"

[dev-dependencies]
tempfile = "3"
